package org.flywaydb.core.api;

public enum ErrorCode {
    FAULT,
    ERROR,
    JDBC_DRIVER,
    DB_CONNECTION,
    DUPLICATE_VERSIONED_MIGRATION,
    DUPLICATE_REPEATABLE_MIGRATION,
    DUPLICATE_UNDO_MIGRATION,
    CONFIGURATION;
}